//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public App()
        {
            this.AppCIs = new HashSet<AppCI>();
            this.vDeptAppDtls = new HashSet<vDeptAppDtl>();
            this.vUserAppDtls = new HashSet<vUserAppDtl>();
            this.AppCIChangeLogs = new HashSet<AppCIChangeLog>();
        }
    
        public int AppID { get; set; }
        public string Name { get; set; }
        public string Manufacturer { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
        public string Language { get; set; }
        public Nullable<int> ScopeID { get; set; }
        public Nullable<int> BeastID { get; set; }
        public Nullable<int> AppDeskID { get; set; }
        public string TechnicalOwner { get; set; }
        public string BusinessOwner { get; set; }
        public string PrimaryTester { get; set; }
        public string SecondaryTester { get; set; }
        public Nullable<bool> LicenseRequired { get; set; }
        public string LicenseOwner { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public System.DateTime ModDt { get; set; }
        public byte[] RowVersion { get; set; }
        public string ModUser { get; set; }
    
        public virtual AppScope AppScope { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppCI> AppCIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vDeptAppDtl> vDeptAppDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vUserAppDtl> vUserAppDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppCIChangeLog> AppCIChangeLogs { get; set; }
    }
}
