//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppCIChangeLog
    {
        public long AppCIChangeLogID { get; set; }
        public Nullable<int> AppCIID { get; set; }
        public Nullable<int> AppID { get; set; }
        public int ChangeTypeID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> DispositionID { get; set; }
        public string CMID { get; set; }
        public string CMModel { get; set; }
        public string Name { get; set; }
        public string Manufacturer { get; set; }
        public string Version { get; set; }
        public string TechnicalOwner { get; set; }
        public string BusinessOwner { get; set; }
        public string PrimaryTester { get; set; }
        public string SecondaryTester { get; set; }
        public string ChangeDescription { get; set; }
        public System.DateTime ModDt { get; set; }
        public byte[] RowVersion { get; set; }
        public string ModUser { get; set; }
        public Nullable<int> PkgStatusID { get; set; }
    
        public virtual App App { get; set; }
        public virtual AppChangeType AppChangeType { get; set; }
        public virtual AppCI AppCI { get; set; }
        public virtual AppDisposition AppDisposition { get; set; }
        public virtual AppStatu AppStatu { get; set; }
        public virtual AppPkgStatu AppPkgStatu { get; set; }
    }
}
