//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppCI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppCI()
        {
            this.AppCIOS = new HashSet<AppCIO>();
            this.AppDependencies = new HashSet<AppDependency>();
            this.AppDependencies1 = new HashSet<AppDependency>();
            this.AppSupersedences = new HashSet<AppSupersedence>();
            this.AppSupersedences1 = new HashSet<AppSupersedence>();
            this.GroupApps = new HashSet<GroupApp>();
            this.MachineApps = new HashSet<MachineApp>();
            this.UserApps = new HashSet<UserApp>();
            this.vDeptAppDtls = new HashSet<vDeptAppDtl>();
            this.vUserAppDtls = new HashSet<vUserAppDtl>();
            this.AppCIChangeLogs = new HashSet<AppCIChangeLog>();
        }
    
        public int AppCIID { get; set; }
        public int AppID { get; set; }
        public string CMID { get; set; }
        public string CMModel { get; set; }
        public string FolderPath { get; set; }
        public string DeploymentTool { get; set; }
        public string DeploymentGroup { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> DispositionID { get; set; }
        public Nullable<bool> RebootReq { get; set; }
        public Nullable<bool> LogonReq { get; set; }
        public string Notes { get; set; }
        public string LicensingInfo { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public System.DateTime ModDt { get; set; }
        public byte[] RowVersion { get; set; }
        public string ModUser { get; set; }
        public Nullable<int> PkgStatusID { get; set; }
    
        public virtual App App { get; set; }
        public virtual AppDisposition AppDisposition { get; set; }
        public virtual AppStatu AppStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppCIO> AppCIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppDependency> AppDependencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppDependency> AppDependencies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppSupersedence> AppSupersedences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppSupersedence> AppSupersedences1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupApp> GroupApps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachineApp> MachineApps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserApp> UserApps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vDeptAppDtl> vDeptAppDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vUserAppDtl> vUserAppDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppCIChangeLog> AppCIChangeLogs { get; set; }
        public virtual AppPkgStatu AppPkgStatu { get; set; }
    }
}
