//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppInventory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AppInventoryEntities : DbContext
    {
        public AppInventoryEntities()
            : base("name=AppInventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<App> Apps { get; set; }
        public virtual DbSet<AppCI> AppCIs { get; set; }
        public virtual DbSet<AppCIO> AppCIOS { get; set; }
        public virtual DbSet<AppDependency> AppDependencies { get; set; }
        public virtual DbSet<AppDisposition> AppDispositions { get; set; }
        public virtual DbSet<AppMSIInfo> AppMSIInfoes { get; set; }
        public virtual DbSet<AppScope> AppScopes { get; set; }
        public virtual DbSet<AppStatu> AppStatus { get; set; }
        public virtual DbSet<AppSupersedence> AppSupersedences { get; set; }
        public virtual DbSet<DeploymentBatch> DeploymentBatches { get; set; }
        public virtual DbSet<DeploymentBatchUser> DeploymentBatchUsers { get; set; }
        public virtual DbSet<DeploymentStatu> DeploymentStatus { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupApp> GroupApps { get; set; }
        public virtual DbSet<GroupMember> GroupMembers { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<MachineApp> MachineApps { get; set; }
        public virtual DbSet<O> OS { get; set; }
        public virtual DbSet<RBACGroup> RBACGroups { get; set; }
        public virtual DbSet<RBACInfo> RBACInfoes { get; set; }
        public virtual DbSet<UserApp> UserApps { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<UserMachine> UserMachines { get; set; }
        public virtual DbSet<UserOwnership> UserOwnerships { get; set; }
        public virtual DbSet<vDeptAppDtl> vDeptAppDtls { get; set; }
        public virtual DbSet<vw_AppCIOSDtl> vw_AppCIOSDtl { get; set; }
        public virtual DbSet<vw_DeptAppDtl> vw_DeptAppDtl { get; set; }
        public virtual DbSet<vw_UserMachineAppActual> vw_UserMachineAppActual { get; set; }
        public virtual DbSet<vw_UserMachineAppNonGlobal> vw_UserMachineAppNonGlobal { get; set; }
        public virtual DbSet<vUserAppDtl> vUserAppDtls { get; set; }
        public virtual DbSet<AppChangeType> AppChangeTypes { get; set; }
        public virtual DbSet<AppCIChangeLog> AppCIChangeLogs { get; set; }
        public virtual DbSet<AppPkgStatu> AppPkgStatus { get; set; }
    
        public virtual ObjectResult<sp_GetAppUsers_Result> sp_GetAppUsers(Nullable<int> appCIID)
        {
            var appCIIDParameter = appCIID.HasValue ?
                new ObjectParameter("appCIID", appCIID) :
                new ObjectParameter("appCIID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAppUsers_Result>("sp_GetAppUsers", appCIIDParameter);
        }
    
        public virtual ObjectResult<sp_GetDeptApps_Result> sp_GetDeptApps(string dEPT_NAME)
        {
            var dEPT_NAMEParameter = dEPT_NAME != null ?
                new ObjectParameter("DEPT_NAME", dEPT_NAME) :
                new ObjectParameter("DEPT_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDeptApps_Result>("sp_GetDeptApps", dEPT_NAMEParameter);
        }
    
        public virtual ObjectResult<sp_GetSupersedingApps_Result> sp_GetSupersedingApps(Nullable<int> appCIID)
        {
            var appCIIDParameter = appCIID.HasValue ?
                new ObjectParameter("appCIID", appCIID) :
                new ObjectParameter("appCIID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSupersedingApps_Result>("sp_GetSupersedingApps", appCIIDParameter);
        }
    
        public virtual ObjectResult<sp_GetUserApps_Result> sp_GetUserApps(string uSER_NAME)
        {
            var uSER_NAMEParameter = uSER_NAME != null ?
                new ObjectParameter("USER_NAME", uSER_NAME) :
                new ObjectParameter("USER_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetUserApps_Result>("sp_GetUserApps", uSER_NAMEParameter);
        }
    }
}
