//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppMSIInfo
    {
        public int AppMSIInfoID { get; set; }
        public string CMID { get; set; }
        public string SourcePath { get; set; }
        public Nullable<bool> SourceValid { get; set; }
        public string FileNameMSI { get; set; }
        public string FileNameMST { get; set; }
        public string ARPManufacturer { get; set; }
        public string ARPDisplayName { get; set; }
        public string ARPVersion { get; set; }
        public string ProductCode { get; set; }
        public string UpgradeCode { get; set; }
        public System.DateTime ModDt { get; set; }
        public byte[] RowVersion { get; set; }
        public string ModUser { get; set; }
    }
}
