//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeploymentBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeploymentBatch()
        {
            this.DeploymentBatchUsers = new HashSet<DeploymentBatchUser>();
        }
    
        public int DeploymentBatchID { get; set; }
        public string Name { get; set; }
        public System.DateTime PlannedDt { get; set; }
        public Nullable<System.DateTime> DeploymentDt { get; set; }
        public string Geo { get; set; }
        public string Team { get; set; }
        public System.DateTime ModDt { get; set; }
        public byte[] RowVersion { get; set; }
        public string ModUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeploymentBatchUser> DeploymentBatchUsers { get; set; }
    }
}
