//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeploymentBatchUser
    {
        public int DeploymentBatchUserID { get; set; }
        public int DeploymentBatchID { get; set; }
        public string UserID { get; set; }
        public string Win7MachineID { get; set; }
        public string Win10MachineID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Comments { get; set; }
        public System.DateTime ModDt { get; set; }
        public byte[] RowVersion { get; set; }
        public string ModUser { get; set; }
    
        public virtual DeploymentBatch DeploymentBatch { get; set; }
        public virtual DeploymentStatu DeploymentStatu { get; set; }
        public virtual Machine Machine { get; set; }
        public virtual Machine Machine1 { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
