//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserApp
    {
        public int UserAppID { get; set; }
        public string UserID { get; set; }
        public int AppCIID { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public Nullable<short> Priority { get; set; }
        public System.DateTime ModDt { get; set; }
        public byte[] RowVersion { get; set; }
        public string ModUser { get; set; }
    
        public virtual AppCI AppCI { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
