//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDeptAppDtl
    {
        public long DeptAppDtlID { get; set; }
        public string Dept { get; set; }
        public string DeptHL { get; set; }
        public int AppCIID { get; set; }
        public int AppID { get; set; }
        public string CMID { get; set; }
        public string CMModel { get; set; }
        public string Manufacturer { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public string FolderPath { get; set; }
        public string Scope { get; set; }
        public System.DateTime ModDt { get; set; }
    
        public virtual App App { get; set; }
        public virtual AppCI AppCI { get; set; }
    }
}
