//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AppCIOSDtl
    {
        public int AppID { get; set; }
        public int AppCIID { get; set; }
        public string CMModel { get; set; }
        public string CMID { get; set; }
        public string Manufacturer { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public string FolderPath { get; set; }
        public int OSID { get; set; }
        public string OS { get; set; }
        public Nullable<int> ScopeID { get; set; }
        public string Scope { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Status { get; set; }
    }
}
